"""LLMInfra: attention, positional encoding, MoE and model building blocks.

The package is organized into subpackages by role:

- `attention`: classic, sparse, linear and hybrid attention variants
- `flashattention`: educational FlashAttention v1-v4 implementations
- `layers`: FFN / norm / SSM / transformer block layers
- `moe`: Mixture-of-Experts components
- `inference`: KV cache, paging and decoding utilities

All public names are re-exported here, so ``from llminfra import X`` works
regardless of the internal layout.
"""

from .attention import (
    AlibiAttention,
    AttentionResidual,
    BaseAttention,
    BlockSparseAttention,
    CompressedSparseAttention,
    FlashMLA,
    GatedDeltaNet,
    GroupQueryAttention,
    HybridAttention,
    LightningAttention,
    LinearAttention,
    MultiHeadAttention,
    MultiHeadLatentAttention,
    MultiQueryAttention,
    RingAttention,
    SlidingWindowAttention,
    distributed_ring_attention,
    ring_attention,
)
from .flashattention import FlashAttention, flash_attention
from .inference import (
    BlockSparseIndexer,
    DSparkDecoder,
    DSparkScheduler,
    EagleSpeculator,
    MultiTokenPredictionHead,
    OnDiskKVStore,
    PagedAttentionCache,
    PagedKVBlockAllocator,
    SpeculativeDecoder,
    TieredKVCache,
    mtp_loss,
    paged_attention,
)
from .layers import (
    FeedForward,
    HybridLayerStack,
    Mamba2Layer,
    Mamba2State,
    RMSNorm,
    SwiGLUFFN,
    TransformerBlock,
)
from .model import CausalLMModel, CausalLMOutput
from .multimodal import (
    CrossAttentionFuser,
    MultimodalCausalLM,
    MultimodalCausalLMOutput,
    VisionEncoderAdapter,
    build_multimodal_position_ids,
)
from .moe import (
    DeepSeekMoE,
    ExpertFFN,
    ExpertParallelMoE,
    LatentMoE,
    MixtureOfExperts,
    TopKRouter,
    load_balance_loss,
)
from .positional import (
    ALiBiBias,
    DynamicNTKRotaryEmbedding,
    LONGROPE_PRESETS,
    LongRoPEPreset,
    LongRoPEScaledRotaryEmbedding,
    MultiModalRotaryPositionEmbedding,
    PartialRotaryPositionEmbedding,
    PositionInterpolation,
    RotaryPositionEmbedding,
    TwoDimensionalPositionEmbedding,
    YaRNParameters,
    YaRNScaledRotaryEmbedding,
    apply_rotary_pos_emb,
    get_longrope_preset,
    get_positional_encoding,
    register_longrope_preset,
)
from .quantization import (
    FakeQuantizer,
    QATWrapper,
    QuantizationConfig,
    build_quantized,
)
from .registry import build_attention, build_positional_encoding, list_attentions

__all__ = [
    "ALiBiBias",
    "AlibiAttention",
    "AttentionResidual",
    "BaseAttention",
    "BlockSparseAttention",
    "BlockSparseIndexer",
    "CausalLMModel",
    "CausalLMOutput",
    "CompressedSparseAttention",
    "DeepSeekMoE",
    "DynamicNTKRotaryEmbedding",
    "DSparkDecoder",
    "DSparkScheduler",
    "EagleSpeculator",
    "ExpertFFN",
    "ExpertParallelMoE",
    "FakeQuantizer",
    "FeedForward",
    "FlashAttention",
    "FlashMLA",
    "GatedDeltaNet",
    "GroupQueryAttention",
    "HybridLayerStack",
    "HybridAttention",
    "LatentMoE",
    "LightningAttention",
    "LinearAttention",
    "LongRoPEScaledRotaryEmbedding",
    "LONGROPE_PRESETS",
    "LongRoPEPreset",
    "Mamba2Layer",
    "Mamba2State",
    "MixtureOfExperts",
    "MultiHeadAttention",
    "MultiHeadLatentAttention",
    "MultiModalRotaryPositionEmbedding",
    "MultiQueryAttention",
    "MultiTokenPredictionHead",
    "MultimodalCausalLM",
    "MultimodalCausalLMOutput",
    "OnDiskKVStore",
    "PagedAttentionCache",
    "PagedKVBlockAllocator",
    "PartialRotaryPositionEmbedding",
    "PositionInterpolation",
    "QATWrapper",
    "QuantizationConfig",
    "RMSNorm",
    "RingAttention",
    "RotaryPositionEmbedding",
    "SlidingWindowAttention",
    "SpeculativeDecoder",
    "SwiGLUFFN",
    "TieredKVCache",
    "TopKRouter",
    "TransformerBlock",
    "TwoDimensionalPositionEmbedding",
    "YaRNParameters",
    "YaRNScaledRotaryEmbedding",
    "apply_rotary_pos_emb",
    "build_multimodal_position_ids",
    "build_attention",
    "build_positional_encoding",
    "build_quantized",
    "flash_attention",
    "get_positional_encoding",
    "get_longrope_preset",
    "list_attentions",
    "load_balance_loss",
    "mtp_loss",
    "paged_attention",
    "ring_attention",
    "distributed_ring_attention",
    "CrossAttentionFuser",
    "VisionEncoderAdapter",
    "register_longrope_preset",
]
